spring:
  config:
    import: optional:file:.env[.properties]  # ✅ dotenv 자동 로드
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  eureka:
    client:
      enabled: false

server:
  port: 8080
